####
#### Use kwalify and this schema to validate the config files.
#### Example:
####    kwalify -f OWLTools-Solr/src/main/resources/config-schema.yaml OWLTools-Solr/src/main/resources/ont-config.yaml
####    kwalify -f config-schema.yaml ont-config.yaml
####
type: map
mapping:
  "id":
    type: str
    required: yes
  "description":
    type: str
    required: yes
  "display_name":
    type: str
    required: yes
  "document_category":
    type: str
    required: yes
  "weight":
    type: int
    required: no
  "default_fields_and_boosts":
    type: str
    required: no
  "searchable_extension":
    type: str
    required: no
  "fields":
    type: seq
    sequence:
      - type: map
        mapping:
          "id":
            type: str
            required: yes
          "description":
            type: str
            required: yes
          "display_name":
            type: str
            required: yes
          "type":
            type: str
            required: yes 
          "required":
            type: bool
            required: no
          "cardinality":
            type: str
            required: no
          "property":
            type: str
            required: yes
          "weight":
            type: int
            required: no
          "transform":
            type: seq
            required: no
            sequence:
              - type: str
          "searchable":
            type: bool
            required: no
