####
#### The ontology description file for GOlr and AmiGO.
####
id: bbop_ont
description: Test mapping of ontology class for GO.
display_name: Ontology
document_category: ontology_class
weight: 40
default_fields_and_boosts: id^2.0 label^2.0 description^1.0 comment^0.5 synonym^1.0 alternate_id^1.0
fields:
  # - id: document_category
  #   description: The category of the document in the Solr index.
  #   display_name: Category
  #   type: string
  #   property_type: fixed
  #   property: ontology_class
  - id: id
    description: Term acc/id.
    display_name: Acc
    type: string
    property: getIdentifier
#    transform: []
#    - boolify
  - id: label
    description: Common term name.
    display_name: Term
    type: string
    #property: http://www.w3.org/2000/01/rdf-schema#label
    property: getLabel
    searchable: true
## Ever used with terms?
# - id: descriptive_name
#     description: Term description.
#     display_name: Description
#     type: string
#     property: descriptive_name
#    searchable: true
  - id: description
    description: Term definition.
    display_name: Definition
    type: string
    property: getDef
    searchable: true
  - id: source
    description: Term namespace.
    display_name: Source
    type: string
    property: getNamespace
  - id: is_obsolete
    description: Is the term obsolete?
    display_name: Obsoletion
    type: boolean
    property: getIsObsoleteBinaryString
  - id: comment
    description: Term comment.
    display_name: Comment
    type: string
    property: getComment
    searchable: true
## looks like single in OWLGraphWrapper API
#    cardinality: multi
  - id: synonym
    description: Term synonym.
    display_name: Synonym
    type: string
    property: getOBOSynonymStrings
    cardinality: multi
    searchable: true
  - id: alternate_id
    description: Alternate term id.
    display_name: Alt ID
    type: string
    property: getAltIds
    cardinality: multi
  - id: subset
    description: Term subset.
    display_name: Subset
    type: string
    property: getSubsets
    cardinality: multi
  - id: definition_xref
    description: Definition cross-reference.
    display_name: Def XRef
    type: string
    property: getDefXref
    cardinality: multi
#  - id: json
#    description: JSON blob.
#    display_name: JSON
#    type: string
#    property: ???
